unique_ids:
  forms:
    Home: RUHGCGVKW7FCMNTXAM4VMQQ3YRQYBTDU
    Inbox: MVY2I4SLNCENBZEY5GSK2X2XVBHHRZDY
    ItemTemplate1: CUZ4LZ623QR4SWXDDCD3UGZWOC5NMPYJ
    Send: '1713834028839219181459397.511'
  modules: {}
  server_modules:
    ServerModule1: 7SP346KCYEQ3SGND54XPEZLPYBK6AE3F
  assets:
    1178287917857263668.png: '1704781715555639478468229.2709'
    standard-page.html: 2ILXDI56MLAKFE3Y5LBASCVI2J4QFHP5
    theme.css: T4YQQCKLTVNSFKW7BSG3XGOATCRF3EVT
  scripts: {}
